name: Welcome and Bye Bye Workflow

on:
  workflow_dispatch:

jobs:
  welcome-bye-bye:
    runs-on: ubuntu-latest

    steps:
    - name: Print Welcome Message
      run: echo "Welcome! This is a manual workflow trigger."

    - name: Perform an Optional Task
      run: echo "Performing some optional tasks here..."

    - name: Print Bye Bye Message
      run: echo "Bye Bye! Workflow complete."
